package com.secufusion.events.entity;

public enum RootCause {
    MALWARE_INFECTION,
    PHISHING_ATTACK,
    POLICY_MISCONFIGURATION,
    USER_ERROR,
    INSIDER_THREAT,
    SYSTEM_VULNERABILITY,
    THIRD_PARTY_BREACH,
    SOCIAL_ENGINEERING,
    CONFIGURATION_DRIFT,
    FALSE_POSITIVE,
    UNKNOWN,
    OTHER
}
