# Gateway App
GATEWAY_NAME: API-GATEWAY-SERVICE
GATEWAY_PORT: 8080

# Eureka
EUREKA_URL: http://localhost:8761/eureka/
EUREKA_REGISTER: true
EUREKA_FETCH: true
EUREKA_PREFER_IP: false

# Service Names
AUTH_SERVICE_NAME: auth-service
IAM_SERVICE_NAME: iam-service
TENANT_SERVICE_NAME: tenant-service
PRODUCT_SERVICE_NAME: product-service

# Service URIs
AUTH_SERVICE_URI: http://localhost:8081
IAM_SERVICE_URI: http://localhost:8082
TENANT_SERVICE_URI: http://localhost:8083
PRODUCT_SERVICE_URI: http://localhost:8084
