# ===============================
# Server
# ===============================
server.port=${GATEWAY_SERVICE_PORT}
server.forward-headers-strategy=framework


# ===============================
# Spring Application
# ===============================
spring.application.name=${GATEWAY_SERVICE_NAME}
spring.config.import=optional:file:${file_path}


# ===============================
# Disable default security
# ===============================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# ===============================
# Spring Cloud Gateway
# ===============================
spring.cloud.gateway.discovery.locator.enabled=false


# ===============================
# CORE SERVICE ROUTES
# ===============================

# IAM SERVICE
spring.cloud.gateway.routes[0].id=IAM-SERVICE
spring.cloud.gateway.routes[0].uri=lb://IAM-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/iam/**

# TENANT SERVICE
spring.cloud.gateway.routes[1].id=TENANT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://TENANT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tenants/**

# EVENTS SERVICE
spring.cloud.gateway.routes[2].id=EVENTS-SERVICE
spring.cloud.gateway.routes[2].uri=lb://EVENTS-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/events/**


# ===============================
# OPENAPI / V3 DOC ROUTES
# ===============================

spring.cloud.gateway.routes[3].id=iam-openapi
spring.cloud.gateway.routes[3].uri=${IAM_SERVICE_URI}
spring.cloud.gateway.routes[3].predicates[0]=Path=/openapi/iam
spring.cloud.gateway.routes[3].filters[0]=SetPath=/api/iam/v3/api-docs

spring.cloud.gateway.routes[4].id=tenant-openapi
spring.cloud.gateway.routes[4].uri=${TENANT_SERVICE_URI}
spring.cloud.gateway.routes[4].predicates[0]=Path=/openapi/tenant
spring.cloud.gateway.routes[4].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.routes[5].id=events-openapi
spring.cloud.gateway.routes[5].uri=${EVENTS_SERVICE_URI}
spring.cloud.gateway.routes[5].predicates[0]=Path=/openapi/events
spring.cloud.gateway.routes[5].filters[0]=SetPath=/v3/api-docs


# ===============================
# Springdoc / Swagger UI (Aggregation)
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=IAM-SERVICE
springdoc.swagger-ui.urls[0].url=/openapi/iam

springdoc.swagger-ui.urls[1].name=TENANT-SERVICE
springdoc.swagger-ui.urls[1].url=/openapi/tenant

springdoc.swagger-ui.urls[2].name=EVENTS-SERVICE
springdoc.swagger-ui.urls[2].url=/openapi/events
